"""add language to posts

Revision ID: 98710b58828d
Revises: bb976aae54dc
Create Date: 2020-07-02 12:31:26.474935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98710b58828d'
down_revision = 'bb976aae54dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
